-- REVENUE: Calculates the total revenue generated by each persona segment.

WITH persona_by_user AS (
    SELECT
        u.udid,
        SUM(i.rev) AS total_spent_cents,
        CASE
            WHEN SUM(i.rev) IS NULL OR SUM(i.rev) = 0 THEN 'free_player'
            WHEN SUM(i.rev) < 2000 THEN 'minnow'
            WHEN SUM(i.rev) < 10000 THEN 'dolphin'
            ELSE 'whale'
        END AS persona
    FROM
        game_jet.users u
    LEFT JOIN
        game_jet.iaps i ON u.udid = i.udid
    GROUP BY
        u.udid
)
SELECT
    persona,
    SUM(total_spent_cents) / 100.0 AS total_revenue_usd
FROM
    persona_by_user
WHERE
    persona <> 'free_player'
GROUP BY
    persona
ORDER BY
    total_revenue_usd DESC;
